### ISSUE TITLE
infrastructure: consider replacing `Vagrant` with `docker`

### ISSUE THREAD

**Issue by sbinet** [go-clang/gen#100]
`Vagrant` is a great tool but it has a lot of dependencies and is somewhat slower to provision VMs than `docker` to provision containers.

For `MacOSX` and `Windows` developers, switching to `docker` shouldn't be an issue.
For `Linux` users, there are only benefits (smaller memory footprint, increased responsivity, etc...)

**Comment by zimmski** [comment]
I see only one problem which I cannot answer: Is it possible to "share" a local directory with a Docker container? The advantage of `Vagrant` is that you can compile/test in the VM while you can code and commit from the outside.

Besides that, creating a Dockerfile is pretty easy since we only need the ubuntu trusty 64bit image as a base and then execute the vagrant scripts.

**Comment by sbinet** [comment]
yep, _e.g_:

```sh
sh> docker run -v `pwd`:/go/src/github.com/go-clang/gen golang:1.5 make
```

(the base image `golang:1.5` might not have everything installed, though, so we'd have to create a, say, `go-clang/build` image)

**Comment by zimmski** [comment]
Cool! Now that I am thinking about it, it just makes sense since I am doing that also in production :D

I used $GOPATH/src/github.com/go-clang btw to sync all repositories.

**Comment by zimmski** [comment]
We considered this a long time ago and said "yes". @zchee has kind of offered to implement this in #130
