### ISSUE TITLE
uint16 wrapping problem in (SourceLocation).ExpansionLocation()

### ISSUE THREAD

**Issue by cmaglie** [go-clang/gen#105]
I'm getting wrong results while parsing large files, in particular if the "offset" in a SourceLocation object goes over 65k the result wraps around when I try to get the value with ```ExpansionLocation()``` method.

I found the problem in the following function https://github.com/go-clang/v3.7/blob/master/clang/sourcelocation_gen.go#L78:

```go
func (sl SourceLocation) ExpansionLocation() (File, uint16, uint16, uint16) {
	var file File
	var line C.uint
	var column C.uint
	var offset C.uint

	C.clang_getExpansionLocation(sl.c, &file.c, &line, &column, &offset)

	return file, uint16(line), uint16(column), uint16(offset)
}
```

where `offset` is cast to `uint16` (losing the high part of the value). I changed the function to

```go
func (sl SourceLocation) ExpansionLocation() (File, uint64, uint64, uint64) {
	var file File
	var line C.uint
	var column C.uint
	var offset C.uint

	C.clang_getExpansionLocation(sl.c, &file.c, &line, &column, &offset)

	return file, uint64(line), uint64(column), uint64(offset)
}
```

and everything works fine again.

I see that the "return" type of ```clang_getExpansionLocation``` is just ```unsigned *```, I suspect that there may be other parts of the bindings that may be affected by the same problem.

**Comment by zimmski** [comment]
I will change the generation on the weekend (I am a little swamped for the next few days). I noticed the problem too in an internal project @work. We simply use the wrong integer wide for some types. E.g. "int" should be 32bit not 16bit.

@sbinet: You can assign the issue to me if you want. I already did a similar change @work. The problem is in https://github.com/go-clang/gen/blob/master/type.go#L65 Short=16bit Int=32bit Long and LongLong=64bit. We thought originally that we should go with the ANSI-C specifications where the types are listed with "at least" definitions.

**Comment by sbinet** [comment]
(didn't manage to carve up some time for this, @zimmski , if you want, it's all yours)

**Comment by zimmski** [comment]
Will take a look. Sorry for being so unresponsive regarding this project I am slowly (slower than a snail) working of my open source issues. Lately it has been a full-time job :-/ Care to privately mail me. I would love to hear about FOSDEM.
